### ISSUE TITLE
[Feature]: Navbar logo link to home

### ISSUE THREAD

**Issue by Haviles04** [cuttle-cards/cuttle#1132]
### Feature Summary

We should make the cuttle logo in the navbar a link

### Detailed Description

We should make the cuttle logo in the navbar a link, this should direct you to home where you can play a game.

Example: You are on `/stats` and click the logo and it brings you to the homepage where you can join a game

**Comment by Aashutosh-Basnet** [comment]
Hi, I'd like to work on this issue. Could you please assign it to me?

**Comment by IbrahimKhanGH** [comment]
Hi! This is my first open source PR 🎉 

I noticed the logo navigation issue and implemented a solution. I wasn't sure about the issue assignment process, but went ahead since it seemed like a straightforward fix. I followed the existing test patterns in the codebase for consistency.

Would love any feedback, guidance, or suggestions for improvement! Thanks for reviewing 😊
