### ISSUE TITLE
[Feature]: Create version endpoint

### ISSUE THREAD

**Issue by byarmis** [cuttle-cards/cuttle#156]
### Feature Summary

Create an API endpoint that returns the current version number

### Detailed Description

This could probably live in a `/healthcheck` or `/api/healthcheck` route, but debugging the deploy with @itsalaidbacklife currently and an endpoint that returns the current version of the deployed code would be handy for testing things out.

Down the line, this endpoint could return if the backend can connect to the database correctly and things like that, but for starters, just the version would be helpful

**Comment by lbalmaceda** [comment]
@byarmis By "version of the deployed code" you mean the version that lives in the package.json file here or where? 
https://github.com/cuttle-cards/cuttle/blob/main/package.json#L3

**Comment by itsalaidbacklife** [comment]
@lbalmaceda yes I think the package.json version would be most appropriate. I think we should use `/status` as the endpoint url and we could put the endpoint in a new file `api/controllers/StatusController.js`

It would be ideal if it could return a json payload that includes both `version` taken from package json as you suggest and `status` indicating whether the server is able to query the database. It could make a simple query like `Game.find({limit: 1})` and set the `status` to "up" if there are no errors and one record is found, and to "down" otherwise

**Comment by itsalaidbacklife** [comment]
Awesome thank you! While we are at it do you think it'd be feasible to include the SHA of the latest commit? I'm not sure how we'd approach it exactly but if we could have all three pieces of info (package version, last commit sha, connectivity status) that would be extremely helpful

**Comment by lbalmaceda** [comment]
Sure! I'll have to understand how the server/api is being built as a deliverable/package. There might be a way to use the git CLI to evaluate and get the latest commit SHA during the "building" step.

**Comment by lbalmaceda** [comment]
I've pushed the changes for the original request. The commit SHA is more challenging as it would mean the server would need to clone this repository and have it available locally for the git CLI to pick it up on runtime. I'll work on a separate PR that branches off this one to try to add a static file during the build process that we can reference to from the introduced controller. I hope that's OK with you!

**Comment by itsalaidbacklife** [comment]
> I've pushed the changes for the original request. The commit SHA is more challenging as it would mean the server would need to clone this repository and have it available locally for the git CLI to pick it up on runtime. I'll work on a separate PR that branches off this one to try to add a static file during the build process that we can reference to from the introduced controller. I hope that's OK with you!

Yeah that's great. We can definitely take this as an initial pass and figure out the git stuff downstream

**Comment by lbalmaceda** [comment]
Continuing the conversation on the SHA value...

We need this value to be available statically. That means it needs to be generated before the server is up.

**Typically, how do you run this server in the host?** 

I see that `npm run start:server` would internally do `node app.js`.

I'm new to Sails but seems there's no "build" step involved. Assuming the host has the `git` CLI installed (otherwise... I don't see how we can obtain the SHA value), I can think of two options:
- Define a bash script that echoes the value to a file or env var, and execute "first" in the `npm run start:server` script.
- Define a Grunt task to do something like that, and hook it in the lifecycle of Sails. I saw that [custom Grunt tasks](https://sailsjs.com/documentation/concepts/assets/default-tasks) could be defined.

**Comment by itsalaidbacklife** [comment]
So we are hosting in heroku and using their [node-buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-nodejs) which can be a bit magical, but after a bit of digging, it looks like we can refer to the sha as an [env var](https://devcenter.heroku.com/changelog-items/630).
```
SOURCE_VERSION
```
should resolve to the SHA when deployed in heroku. That does however beg questions about what to do for localhost development. It may make sense to simply make the fallback be graceful when that value's not set. But we could alternatively configure the `start:server` script to set that variable

**Comment by seriouslysean** [comment]
It would also be nice to add the version to the `window.cuttle` namespace, like how to do for `app`. This way you could potentially just do `window.cuttle.version` to get the version in the dev console.

**Comment by seriouslysean** [comment]
@itsalaidbacklife we could also switch to a github action based deployment to Heroku that could add the sha in a variety of ways before the deploy, possibly as part of the webpack (or rollup) pipline.

https://github.com/marketplace/actions/deploy-to-heroku

If you look at something like that we could run a separate npm script to grab the sha, make a standalone file, prepend the sha to our js bundle or anything else really. Lots of options :)

**Comment by itsalaidbacklife** [comment]
Closed by #161

**Comment by itsalaidbacklife** [comment]
Created #180 to follow up on the SHA feature
