### ISSUE TITLE
[Feature]: Create Separate url links for login vs signup

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#235]
### Feature Summary

Currently the cuttle.cards/#/login url is used for both login and signup. We should make a separate cuttle.cards/#/signup url that is specifically for signup.

### Detailed Description

The `client/js/views/Login.vue` component is configurable for the login and signup modes. Rather than this being a piece of data internal to the component, this mode could be a computed property that's calculated from `this.$currentRoute` in order to pay attention to these two routes, then add an additional route to `client/js/router/index.js` for the /signup route

**Comment by gulyapulya** [comment]
Hi, I would like to work on this issue, but I do not think I understand it fully... I get that I should add a new route to the client/js/router/index.js, then separate signup from the client/js/views/LoginSignup.vue by creating a new view. However, could you please elaborate more on the "Rather than this being a piece of data internal to the component, this mode could be a computed property that's calculated from this.$currentRoute in order to pay attention to these two routes..."?

**Comment by itsalaidbacklife** [comment]
@gulyapulya this comes down to a concept in vue called [computed properties](https://v2.vuejs.org/v2/guide/computed.html). The basic idea is that we can have a calculation defined that reads other existing data (in this case the route using `this.$currentRoute`) which automatically update if any of the data they depend on updates. 

So for this issue, we actually don't necessarily need a new component for login vs signup for this reason. We can update the router so that two separate urls (/signup and /login) both point to `LoginSignup.vue`, and then we can update `LoginSignup.vue` so that this component pays attention to the current route and configures itself to do the login/signup functionality based on which route its pointed to.

**Comment by itsalaidbacklife** [comment]
Granted as I think further on it, it would be completely reasonable to use separate components instead. Either way works for me

**Comment by seriouslysean** [comment]
Done!
